# This is a sample build configuration for C++ – Make.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: gcc:6.1

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - apt-get update
          - apt-get install -y cmake
          - apt-get install -y libatlas-base-dev
          - apt-get install -y libsuitesparse-dev
          - apt-get install -y python-numpy # for testing only
          - mkdir build && cd build
          - cmake ..
          - make all
          - ctest -V
